/**
 * About Me Section Data
 * Content for expertise cards and technology details
 */

export const expertiseCards = [
  {
    id: 'frontend-architecture',
    icon: 'fas fa-code',
    title: 'Front-End Architecture',
    description: 'Building scalable, maintainable front-end systems with clean architecture and best practices.',
    metric: '17+',
    metricLabel: 'Years Experience',
  },
  {
    id: 'accessibility',
    icon: 'fas fa-universal-access',
    title: 'Accessibility First',
    description: 'WCAG 2.2 AA compliant experiences that are inclusive, usable, and built for everyone.',
    metric: 'WCAG 2.2 AA',
    metricLabel: 'Compliance Focus',
  },
  {
    id: 'performance',
    icon: 'fas fa-tachometer-alt',
    title: 'Performance Driven',
    description: 'Optimized for speed, Core Web Vitals, and exceptional user experiences.',
    metric: '90+',
    metricLabel: 'Lighthouse Score',
  },
  {
    id: 'design-systems',
    icon: 'fas fa-layer-group',
    title: 'Design Systems',
    description: 'Creating scalable design systems and component libraries that drive consistency.',
    metric: '100+',
    metricLabel: 'Components Built',
  },
  {
    id: 'ai-tools',
    icon: 'fas fa-brain',
    title: 'AI & Modern Tools',
    description: 'Leveraging AI and modern tools to build faster, smarter, and more efficient solutions.',
    metric: 'Always Learning',
    metricLabel: 'Staying Ahead',
  },
];

export const technologies = [
  {
    id: 'react',
    name: 'React',
    techName: 'react',
    icon: 'fab fa-react',
    level: 'Expert',
    description: 'Modern React for building scalable interfaces, dashboards, reusable components, and complex application workflows.',
    experience: '10+ Years Experience',
    uses: [
      'Functional Components',
      'Hooks & Custom Hooks',
      'Redux & Context',
      'React Router',
    ],
    projects: [
      'VirtuEd Platform',
      'PipelineOS',
      'Andor Health',
    ],
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    techName: 'typescript',
    icon: 'fab fa-js',
    level: 'Advanced',
    description: 'Type-safe front-end development that improves reliability, maintainability, refactoring, and developer experience.',
    experience: '5+ Years Experience',
    uses: [
      'Interfaces & Types',
      'Typed Component Props',
      'Generics',
      'API Data Models',
    ],
    projects: [
      'PipelineOS',
      'VirtuEd Platform',
      'Healthcare Applications',
    ],
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    techName: 'javascript',
    icon: 'fab fa-js',
    level: 'Expert',
    description: 'Modern JavaScript for building interactive, performant web applications and maintainable front-end systems.',
    experience: '17+ Years Experience',
    uses: [
      'ES6+ Features',
      'Async/Await',
      'DOM & Events',
      'Modules & Bundlers',
    ],
    projects: [
      'VirtuEd Platform',
      'PipelineOS',
      'Andor Health',
    ],
  },
  {
    id: 'html5',
    name: 'HTML5',
    techName: 'html5',
    icon: 'fab fa-html5',
    level: 'Expert',
    description: 'Semantic HTML for accessible, resilient, SEO-friendly, and maintainable digital experiences.',
    experience: '17+ Years Experience',
    uses: [
      'Semantic Landmarks',
      'Accessible Forms',
      'Native Elements',
      'Progressive Enhancement',
    ],
    projects: [
      'Portfolio 2026',
      'VirtuEd Platform',
      'Bonnier Websites',
    ],
  },
  {
    id: 'css3',
    name: 'CSS3',
    techName: 'css3',
    icon: 'fab fa-css3-alt',
    level: 'Expert',
    description: 'Modern CSS for responsive interfaces, scalable design systems, advanced layouts, and maintainable visual architecture.',
    experience: '17+ Years Experience',
    uses: [
      'Grid & Flexbox',
      'Custom Properties',
      'Container Queries',
      'Native Nesting',
    ],
    projects: [
      'Portfolio 2026',
      'PipelineOS',
      'Bonnier Design System',
    ],
  },
  {
    id: 'ai',
    name: 'AI',
    techName: 'ai',
    icon: 'fas fa-brain',
    level: 'Advanced',
    description: 'AI-assisted development for research, prototyping, auditing, architecture, and faster delivery without sacrificing quality.',
    experience: 'Advanced Daily Use',
    uses: [
      'GitHub Copilot',
      'Claude Code',
      'Figma Make',
      'Code & UX Audits',
    ],
    projects: [
      'PipelineOS',
      'Portfolio 2026',
      'Hotelio',
    ],
  },
  {
    id: 'git',
    name: 'Git',
    techName: 'git',
    icon: 'fab fa-git-alt',
    level: 'Advanced',
    description: 'Source control and collaborative workflows for feature development, reviews, releases, and reliable project history.',
    experience: '15+ Years Experience',
    uses: [
      'Feature Branches',
      'Pull Requests',
      'Merge Resolution',
      'Release Workflows',
    ],
    projects: [
      'VirtuEd Platform',
      'PipelineOS',
      'Portfolio 2026',
    ],
  },
  {
    id: 'figma',
    name: 'Figma',
    techName: 'figma',
    icon: 'fab fa-figma',
    level: 'Advanced',
    description: 'Interface design, prototyping, design systems, responsive layouts, and developer-ready product specifications.',
    experience: '8+ Years Experience',
    uses: [
      'Auto Layout',
      'Components & Variants',
      'Design Tokens',
      'Dev Mode',
    ],
    projects: [
      'PipelineOS',
      'Hotelio',
      'Portfolio 2026',
    ],
  },
];
